# Generated by Django 4.0.5 on 2022-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='numero_banios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
